package com.icms.party.enums;

public enum EmailMessageEnum {

	REGISTRATION_SUCCESS,
	REGISTRATION_APPROVAL, 
	REGISTRATION_REJECTION,
	REGISTRATION_FEE,
	ID_RECOVERY,
	PASSWORD_RECOVERY,
	CHANGE_USERNAME,
	CHANGE_PASSWORD,
	NEW_SECONDARY_USER,
	NOTIFICATION,
	ERROR_SENDING_MAIL,
	STIP_APPROVAL_NOTICE,
	DOCUMENT_FILING,
	CLAIM_CREATION,
	MANAGED_CARE,
	CASE_CREATION,
	CASE_FILING,
	INSURER_CLOSURE,
	SELF_INSURER_CLOSURE,
	GROUP_FUND_CLOSURE,
	MFR_RECEIPT,
	NON_CLAIM_NOTIFICATION,
	/* Fix #2781 */
	PARTY_DOCUMENT_FILING,
	//CLAIM_DOCUMENT_FILING,
	INVALID_SENDER,
	CLAIM_02_CHANGE_REJECT,
	NON_STANDARD_FORMAT,
	EDI_FILE_NOT_EXIST,
	NULL_JCN,
	NOT_VALID_JCN,
	ATTORNEY_LEAVE_ABSENCE,
	LATEST_TXN_NOT_FOUND,
	DOCUMENT_PROCESSED,
	/* Fix #2781 */
	GEORGIA_EDI_SLA,
	LICENSURE_DOCUMENT_FILING,
	REHAB_NEW_SUPPLIER_REGISTRATION,
	REHAB_RENEWAL_SUPPLIER_REGISTRATION,
	VIRUS_DETECTION,
	EDI_FILE_VIRUS_DETECTION,
	INVALID_FILE_HAVING_SSN;

}